version: "3.9"
services:

  lamina1:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PUBLIC_IP: ${PUBLIC_IP}
    restart: unless-stopped
    volumes:
      - /root/.lamina1:/root/.lamina1